// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxeOqRHuoNn5KT_t2XGAam6eS0CZOzPmQ',
    appId: '1:128949369655:web:db9ef7c341c860a50778b2',
    messagingSenderId: '128949369655',
    projectId: 'fleetmaptracker',
    authDomain: 'fleetmaptracker.firebaseapp.com',
    storageBucket: 'fleetmaptracker.appspot.com',
    measurementId: 'G-EZ2SL1DEBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDixtWWY7DQawc3ltgBILYH--07gH0D3jk',
    appId: '1:128949369655:android:1e60e27b962242d50778b2',
    messagingSenderId: '128949369655',
    projectId: 'fleetmaptracker',
    storageBucket: 'fleetmaptracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3gfB1nFkYhzWAoPTDz6BZhX2Losec8no',
    appId: '1:128949369655:ios:bd5a56ef306e13310778b2',
    messagingSenderId: '128949369655',
    projectId: 'fleetmaptracker',
    storageBucket: 'fleetmaptracker.appspot.com',
    iosBundleId: 'com.example.fleetMapTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3gfB1nFkYhzWAoPTDz6BZhX2Losec8no',
    appId: '1:128949369655:ios:fc78edc0c55dd5400778b2',
    messagingSenderId: '128949369655',
    projectId: 'fleetmaptracker',
    storageBucket: 'fleetmaptracker.appspot.com',
    iosBundleId: 'com.example.fleetMapTracker.RunnerTests',
  );
}
